### ISSUE TITLE
jsxImport fails for components importing css

### ISSUE THREAD

**Issue by dhowe** [vadimdemedes/import-jsx#12]
Have things working correctly for basic React components using esm/import, however jsxImport() fails (with _SyntaxError: Unexpected token ._) when the target file imports an .css file:

```
import React from "react";
import PropTypes from "prop-types";
import Typography from "@material-ui/core/Typography/Typography";
import Grid from "@material-ui/core/Grid/Grid";
import Slider from "@material-ui/core/Slider";

import "./OcProfile.css"; // fails here

function OcProfile(props) {
  return ( ... )
}
```

Is there perhaps a babel option I need ? And if so, how/where to specify ? 

thanks!

**Comment by vadimdemedes** [comment]
I don't have time currently to investigate this, so I would encourage you to fork and try to find the cause of this and submit a fix!
