### ISSUE TITLE
Is there no way to use config file for more plugins

### ISSUE THREAD

**Issue by nolandg** [vadimdemedes/import-jsx#13]
I see this pull https://github.com/vadimdemedes/import-jsx/pull/8 seems to have disabled the config file. How then can we use additional plugins, like `@babel/plugin-proposal-class-properties`?

Thanks!

**Comment by vadimdemedes** [comment]
There's no way to use more Babel plugins intentionally, because then this module would basically become a clone of [@babel/register](https://babeljs.io/docs/en/babel-register). Goal of this module is to provide zero-config, quick way to import files that contain JSX.
