### ISSUE TITLE
md4 will be disallowed by default in Node.js 17

### ISSUE THREAD

**Issue by BethGriggs** [vadimdemedes/import-jsx#16]
After consideration of OpenSSL's support timelines, Node.js 17 (released this week) will include OpenSSL 3.0. The OpenSSL 3.0 update restricts the usage of some algorithms which are considered legacy,  including `md4`. 

Raising an issue here as I have tracked a few test failures in downstream modules to this module's usage of `md4` in https://github.com/vadimdemedes/import-jsx/blob/28687c2761b0df5551414e9b3c75033171d8ed8d/cache.js#L23

In Node.js 17, we have added a command-line option as a temporary workaround to link to the legacy OpenSSL provider which will enable some of these restricted algorithms. `$ ./node --openssl-legacy-provider  -p 'crypto.createHash("md4")'`, or via `NODE_OPTIONS=--openssl-legacy-provider`. 

I think the ideal outcome would be to update to use a stronger algorithm.

**Comment by mcollina** [comment]
@vadimdemedes would you be available to work on this?

**Comment by Eomm** [comment]
There is an open PR for this https://github.com/vadimdemedes/import-jsx/pull/17

@vadimdemedes would you mind to review it?

**Comment by vadimdemedes** [comment]
Thanks for reporting this! This was resolved in https://github.com/vadimdemedes/import-jsx/pull/17 and released in `4.0.1`.
