### ISSUE TITLE
caching?

### ISSUE THREAD

**Issue by isaacs** [vadimdemedes/import-jsx#5]
Would you be interested in a PR to add caching to save the babel transpilation step in subsequent runs?

I'm thinking it could hash the contents of the file, then save the transpiled source at `.import-jsx-cache/${hash}.js`, and if that file exists, just read it instead of calling into babel.

It'd take some benchmarking to see if or how much it actually improves things, but if you're running the same pile of tests over and over again, I imagine it might be worth exploring.

**Comment by vadimdemedes** [comment]
That would be great indeed!

> I'm thinking it could hash the contents of the file, then save the transpiled source at .import-jsx-cache/${hash}.js, and if that file exists, just read it instead of calling into babel.
I would recommend putting it into `node_modules/.cache/import-jsx`, as that kind of became a standard place for caching. 

It's also important to include import-jsx version and babel config along with file content to hash as a cache key.

> It'd take some benchmarking to see if or how much it actually improves things, but if you're running the same pile of tests over and over again, I imagine it might be worth exploring.
I think the improvements would be quite significant, especially if import-jsx `require()`ed babel and its plugins on-demand, only when transpilation is required.

**Comment by vadimdemedes** [comment]
Released in 4.0.0!
