### ISSUE TITLE
"SyntaxError: Unexpected identifier" when importing a JSX file

### ISSUE THREAD

**Issue by edelgado** [vadimdemedes/import-jsx#7]
I'm trying to create an https://github.com/vadimdemedes/ink app from scratch. In my main package file, I'm importing a JSX file, like you do in the https://github.com/vadimdemedes/create-ink-app project:

```js
const ui = importJsx('./ui');
```

My `ui.js` file begins with these import:

```js
import React, {Component} from 'react';
import PropTypes from 'prop-types';
import {render, Color} from 'ink';
```

When running my cli app, the `importJsx` call, emits this error:

```
ink_demo/ui.js:1
(function (exports, require, module, __filename, __dirname) { import React, { Component } from 'react';
                                                                     ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Module.module._compile.source (/ink_demo/node_modules/import-jsx/index.js:60:11)
    at Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Object.require.extensions.(anonymous function).module (/ink_demo/node_modules/import-jsx/index.js:64:3)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
```

As if `importJSX` didn't understand ES6 code.

I added the `babel` configuration to my `package.json` file:
```js
  "babel": {
    "presets": [
      "@babel/preset-react",
      [
        "@babel/preset-env",
        {
          "targets": {
            "node": true
          }
        }
      ]
    ]
  }
```

Without luck. My sample app is available at https://github.com/edelgado/ink_demo if it helps.

Thanks!

**Comment by maurer2** [comment]
Hello, it works with the following external babel config file: 

```
module.exports = {
  presets: [
    "@babel/preset-react",
    "@babel/preset-env",
  ],
};

```
Additionally in your 'ui.js' you need to use common.js export e.g. `module.exports = Counter;`

You probablt need to install some babel dependencies like `@babel/cli`, `@babel/preset-env`, `@babel/preset-react` and  `@babel/core`

**Comment by vadimdemedes** [comment]
I think it's the `import` that's not supported, which `import-jsx` doesn't transpile. Use `require('...')` to import files instead.
